// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05GekWe0YaqI8R2iX4wDVmqnqElpxyls',
    appId: '1:430982492756:web:0e3d2cc06ec9c58b7bb3c1',
    messagingSenderId: '430982492756',
    projectId: 'instagram-clone-63e52',
    authDomain: 'instagram-clone-63e52.firebaseapp.com',
    storageBucket: 'instagram-clone-63e52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWV1Hurz8uw2WGXijz36EcY5r5h2aZpgU',
    appId: '1:430982492756:android:7c882fdf69fc1c897bb3c1',
    messagingSenderId: '430982492756',
    projectId: 'instagram-clone-63e52',
    storageBucket: 'instagram-clone-63e52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI-p9QBm86rbWvxQGMAvajUeodTZ7KyYk',
    appId: '1:430982492756:ios:cb4c9abfda46d4897bb3c1',
    messagingSenderId: '430982492756',
    projectId: 'instagram-clone-63e52',
    storageBucket: 'instagram-clone-63e52.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI-p9QBm86rbWvxQGMAvajUeodTZ7KyYk',
    appId: '1:430982492756:ios:9e05d496a11255de7bb3c1',
    messagingSenderId: '430982492756',
    projectId: 'instagram-clone-63e52',
    storageBucket: 'instagram-clone-63e52.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
